# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 07:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_phone', models.CharField(max_length=13)),
                ('authUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wbot.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_phone', models.CharField(max_length=13)),
                ('bot_otp', models.CharField(max_length=7)),
                ('bot_pwd', models.CharField(max_length=60)),
                ('bot_state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('message_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('csvFile', models.FileField(upload_to='')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wbot.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phon_num', models.CharField(max_length=13)),
                ('status', models.IntegerField(default=0)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wbot.Bot')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wbot.Message')),
            ],
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNum', models.CharField(max_length=13)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wbot.Bot')),
            ],
        ),
        migrations.AddField(
            model_name='adminbot',
            name='bot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wbot.Bot'),
        ),
    ]
