# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_state',
            field=models.IntegerField(default=0),
        ),
    ]
