# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbot', '0003_message_startedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='csvFile',
            field=models.CharField(max_length=1000),
        ),
    ]
