# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbot', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='auto_pseudoid',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
