# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbot', '0006_document_auto_pseudoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='auto_pseudoid',
            field=models.CharField(blank=True, editable=False, max_length=7, unique=True),
        ),
    ]
