# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbot', '0007_auto_20171216_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
